version: '3.1'

services:
  db:
    image: postgres
    # restart: always
    environment:
      - POSTGRES_USER=matcha
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=matcha
    ports:
      - 5432:5432

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080
    volumes:
      - ./database.sql:/var/www/html/adminer.sql:ro
